### ISSUE TITLE
Explain to check “Allow Scripts to Write Files and Access Network”

### ISSUE THREAD

**Issue by seblavoie** [ff6347/hershey-monoline-text-issues#1]
You might want to point out in the documentation that the user needs to enable _Allow Scripts to Write Files and Access Network_. It took me a little time to figure it out since I had my _Enable JavaScript Debugger_ preference checked and my _Allow Scripts to Write Files and Access Network_ unchecked. 

Otherwise good job :+1:

**Comment by ff6347** [comment]
Oh. Yeah that's right. I totally forgot about it. The icons need to be created. Thanks

**Comment by ff6347** [comment]
fixed with version 0.1.6 
- checks for read write access and warns  
- updated documentation
